spring.application.name=worldwidefm
server.port=8080
radio.browser.base-url=https://de1.api.radio-browser.info/json
radio.browser.timeout=5
radio.browser.cache.ttl=300
radio.browser.cache.max-size=500