spring.application.name=worldwidefm
server.port=8080

# Radio Browser API base URL
radio.browser.base-url=https://de1.api.radio-browser.info/json

# WebClient timeout (seconds)
radio.browser.timeout=5

# Cache TTL (seconds) ? 5 minutes
radio.browser.cache.ttl=300
radio.browser.cache.max-size=500